[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
   "flask>=3.1.2",
   "python-telegram-bot==20.6",
   "telegram>=0.0.1",
   "requests==2.32.3",
]

